/*
Copyright (C) 2025 QuantumNous

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program. If not, see <https://www.gnu.org/licenses/>.

For commercial licensing, please contact support@quantumnous.com
*/

const baseTime = Math.floor(Date.now() / 1000);

export const usageLogMockData = [
  {
    id: 990001,
    created_at: baseTime - 42,
    type: 2,
    user_id: 18,
    username: 'metainsight',
    token_name: 'Claude Code 主力令牌',
    model_name: 'claude-sonnet-4-5',
    quota: 42800,
    prompt_tokens: 12840,
    completion_tokens: 2160,
    use_time: 8,
    is_stream: true,
    channel: 17,
    channel_name: 'Anthropic · 东京',
    group: 'pro',
    request_id: 'req_mock_claude_7f3a9d',
    upstream_request_id: 'msg_mock_01JZ7P9Y2X',
    ip: '114.93.***.21',
    content: '请求完成，缓存命中率 58.4%',
    other: {
      frt: 684,
      cache_tokens: 7500,
      cache_creation_tokens: 2048,
      cache_creation_tokens_5m: 2048,
      group_ratio: 0.8,
      model_ratio: 1.5,
      completion_ratio: 5,
      request_path: '/v1/messages',
      claude: true,
      stream_status: { status: 'ok', end_reason: 'end_turn', error_count: 0 },
      admin_info: {
        use_channel: [12, 17],
        channel_affinity: {
          rule_name: '会话亲和',
          selected_group: 'pro',
          key_source: 'header',
          key_path: 'x-session-id',
          key_hint: 'claude-code-session',
        },
      },
    },
  },
  {
    id: 990002,
    created_at: baseTime - 185,
    type: 2,
    user_id: 27,
    username: 'linxiaoyu',
    token_name: 'Cursor 日常开发',
    model_name: 'gpt-5',
    quota: 4000,
    prompt_tokens: 7,
    completion_tokens: 49,
    use_time: 2,
    is_stream: true,
    channel: 23,
    channel_name: 'OpenAI · 新加坡',
    group: 'default',
    request_id: 'req_mock_gpt5_21bc88',
    upstream_request_id: 'chatcmpl_mock_9C3B',
    ip: '183.6.***.104',
    other: {
      frt: 312,
      cache_tokens: 0,
      cache_creation_tokens: 0,
      group_ratio: 0.8,
      model_ratio: 0.625,
      completion_ratio: 8,
      request_path: '/v1/chat/completions',
      stream_status: { status: 'ok', end_reason: 'stop', error_count: 0 },
      admin_info: { use_channel: [23] },
    },
  },
  {
    id: 990003,
    created_at: baseTime - 438,
    type: 5,
    user_id: 31,
    username: 'student-ai-lab',
    token_name: '课程实验 Key',
    model_name: 'gemini-2.5-pro',
    quota: 0,
    prompt_tokens: 1824,
    completion_tokens: 0,
    use_time: 31,
    is_stream: false,
    channel: 9,
    channel_name: 'Gemini · 官方',
    group: 'student',
    request_id: 'req_mock_error_f91e02',
    upstream_request_id: 'gemini_mock_error_429',
    ip: '120.230.***.8',
    content: '上游触发速率限制，请稍后重试',
    other: {
      cache_tokens: 1024,
      cache_creation_tokens: 0,
      group_ratio: 0.5,
      model_ratio: 1.25,
      request_path: '/v1beta/models/gemini-2.5-pro:generateContent',
      stream_status: {
        status: 'error',
        end_reason: 'upstream_429',
        error_count: 1,
        end_error: 'RESOURCE_EXHAUSTED',
      },
      admin_info: { use_channel: [6, 8, 9] },
    },
  },
  {
    id: 990004,
    created_at: baseTime - 810,
    type: 1,
    user_id: 18,
    username: 'metainsight',
    token_name: '',
    model_name: '',
    quota: 5000000,
    prompt_tokens: 0,
    completion_tokens: 0,
    use_time: 0,
    is_stream: false,
    channel: 0,
    channel_name: '',
    group: 'pro',
    request_id: 'pay_mock_20260712_0018',
    ip: '114.93.***.21',
    content: '在线充值到账 · 支付宝',
    other: {
      admin_info: { payment_method: 'alipay', node_name: 'payment-sh-01' },
    },
  },
  {
    id: 990005,
    created_at: baseTime - 1260,
    type: 6,
    user_id: 27,
    username: 'linxiaoyu',
    token_name: 'Midjourney 绘图',
    model_name: 'midjourney',
    quota: 12000,
    prompt_tokens: 0,
    completion_tokens: 0,
    use_time: 0,
    is_stream: false,
    channel: 36,
    channel_name: 'MJ · 绘图集群',
    group: 'default',
    request_id: 'task_mock_refund_42d103',
    ip: '183.6.***.104',
    content: '异步绘图任务失败，额度已自动退回',
    other: {
      task_id: 'mj_mock_task_1098',
      reason: '上游任务超时',
      group_ratio: 0.8,
      admin_info: { use_channel: [36] },
    },
  },
];
